### ISSUE TITLE
Check for changes before publishing

### ISSUE THREAD

**Issue by Turbo87** [mingyang91/huawei-cloud-api-definitions#1]
👋  the crates.io team noticed that you are publishing quite a few versions of these packages per day and it looks like the majority of these new versions don't actually have any new changes aside from the version number update. We would like to suggest to adjust your scripts to only publish new versions if there are actual changes in the packages that you are publishing. This will make it less noisy for your users and the index files (for example: https://github.com/rust-lang/crates.io-index/blob/master/hu/aw/huawei-cloud-api-definitions-as) won't grow quite as fast.

if you need inspiration, I've recently developed something similar (https://github.com/Turbo87/aws-ip-ranges/blob/main/.github/workflows/update.yml) that uses `git diff` to figure out if there are changes in the repository before it calls `cargo publish`. you could probably adjust that to check for changes only in your schemas subfolders.

**Comment by mingyang91** [comment]
thank you for your notice, that’s helpful , I will try your way in my publish script to pre-check if api real updated.

**Comment by mingyang91** [comment]
Hi, I've fixed this. Now, the publish script will only check the sub-crate if it's been updated, as indicated by the `git logs`. If the issue persists, please reopen this.
